### ISSUE TITLE
Not retrieving any lyrics

### ISSUE THREAD

**Issue by kudolev** [NetNerd/MB_VocaDbLyrics#17]
Hi, I'm currently trying to use the plugin to get lyrics for PowapowaP songs (with the artist name ぽわぽわP just as in vocaDB) and I can't seem to get it to work. 

I already checked that the song and artist names were identical in my mp3 file and the vocaDB site, and that the songs had lyrics posted on vocaDB. I don't know what I could be missing.

**Comment by NetNerd** [comment]
Hi, the plugin seems to be working still in a couple of quick tests. Can you please check your "artist whitelist" setting?  
The default setting is sub-optimal due to it only containing voice names, not producers. This isn't an easy thing to change because a list of all producers would be unimaginably long.

If it is the whitelist causing issues, it should be solved by doing any of the following:
* Add ぽわぽわP to the whitelist
* Remove the whitelist entirely
* Create [multiple artist tags](https://musicbee.fandom.com/wiki/Tagging#Multiple_Value_Tags) so that both ぽわぽわP and the voice used can be seen by the plugin. (most commonly used voicebanks should match against the default setting)

**Comment by NetNerd** [comment]
Closing the issue due to inactivity. If the above things don't help, it can be reopened.
